=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/request-xsd-2026-09-11/download/xmlnyugtacreate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlnyugtacreate" xmlns:tns="http://www.szamlazz.hu/xmlnyugtacreate" elementFormDefault="qualified">

    <complexType name="beallitasokTipus">
        <all>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="pdfLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
        </all>
    </complexType>

    <complexType name="fejlecTipus">
        <all>
            <element name="hivasAzonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="elotag" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="penznem" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="devizaarf" type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="devizabank" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="pdfSablon" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="fokonyvVevo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="rendelesSzam" type="string" maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>

    <complexType name="tetelTipus">
        <all>
            <element name="megnevezes" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="mennyiseg" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiEgyseg" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="nettoEgysegar" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afakulcs" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="netto" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afa" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="brutto" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="fokonyv" type="tns:tetelFokonyvTipus" maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>

    <complexType name="tetelFokonyvTipus">
        <all>
            <element name="arbevetel" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="afa" type="string" maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>
    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel" type="tns:tetelTipus" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>
    
    <!-- jóváírások -->
    <complexType name="kifizetesTipus">
        <all>
            <element name="fizetoeszkoz"          type="string"               maxOccurs="1" minOccurs="1"></element>
            <element name="osszeg"                type="double"               maxOccurs="1" minOccurs="1"></element>
            <element name="leiras"                type="string"               maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>
    <complexType name="kifizetesekTipus">
        <sequence>
            <element name="kifizetes"             type="tns:kifizetesTipus"   maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>


    <element name="xmlnyugtacreate">
        <complexType>
            <all>
                <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="tetelek" type="tns:tetelekTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="kifizetesek" type="tns:kifizetesekTipus" maxOccurs="1" minOccurs="0"></element>
            </all>
        </complexType>
    </element>

</schema>

=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/requests/xmlnyugtacreate.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlnyugtacreate xmlns="http://www.szamlazz.hu/xmlnyugtacreate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.szamlazz.hu/szamla/docs/xsds/nyugtacreate/xmlnyugtacreate.xsd">
  <beallitasok>                                                      <!-- REQ         -->
    <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
    <pdfLetoltes>false</pdfLetoltes>                       <!-- REQ boolean --> <!-- PDF download -->
  </beallitasok>
  <fejlec>                                                <!-- REQ         -->
    <hivasAzonosito></hivasAzonosito>     <!--     string  --> <!-- unique identifier of the call, duplication must be avoided-->
    <elotag>NYGTA</elotag>                    <!-- REQ string  --> <!-- receipt number prefix, required ==> NYGTA-2017-111 -->
    <fizmod>készpénz</fizmod>               <!-- REQ string  --> <!-- payment method, free text field, values ​​used on the interface are: átutalás, készpénz, bankkártya, csekk, utánvét, ajándékutalvány, barion, barter, csoportos beszedés, OTP Simple, kompenzáció, kupon, PayPal,PayU, SZÉP kártya, utalvány -->
    <penznem>Ft</penznem>                   <!-- REQ string  --> <!-- currency: Ft, HUF, EUR, USD stb. -->
    <devizabank>MNB</devizabank>         <!--     string  --> <!-- in case of foreign bill (not Ft/HUF) the name of the Bank -->
    <devizaarf>0.0</devizaarf>                 <!--     string  --> <!-- exchange rate -->
    <megjegyzes></megjegyzes>             <!--     string  --> <!-- free text description,  shown on the receipt -->
    <pdfSablon></pdfSablon>                   <!--     string  --> <!--  optional: custom PDF template ID (A=default A4, J=ticket, L=ticket with logo, N=80 mm); empty or invalid → default (A)-->
    <fokonyvVevo></fokonyvVevo>                      <!--     string  --> <!-- general ledger ID of the customer -->
    <rendelesSzam></rendelesSzam>               <!--     string  --> <!-- order number on receipt -->
  </fejlec>
  <tetelek>                                        <!-- REQ         -->
    <tetel>                                         <!-- REQ         --> <!-- at least one item is required to issue a receipt  -->
      <megnevezes>Kitten doormat</megnevezes>         <!-- REQ string  --> <!-- name of the receipt -->
      <azonosito></azonosito>                                        <!--     string  --> <!-- ID of the receipt -->
      <mennyiseg>2.0</mennyiseg>                               <!-- REQ double  --> <!-- item quantity -->
      <mennyisegiEgyseg>db</mennyisegiEgyseg>          <!-- REQ string  --> <!-- unit of quantity -->
      <nettoEgysegar>10000</nettoEgysegar>                <!-- REQ double  --> <!-- net unit price -->
      <afakulcs>27</afakulcs>                                 <!-- REQ string  --> <!-- VAT rate, values: 0, 5, 10, 27, AAM, TAM, EU, EUK, MAA, F.AFA, K.AFA, ÁKK,HO, EUE, EUFADE, EUFAD37, ATK, NAM, EAM, KBAUK, KBAET -->
      <netto>20000.0</netto>                                 <!-- REQ double  --> <!-- net value (quantity * net unit price) -->
      <afa>5400.0</afa>                                                <!-- REQ double  --> <!-- VAT total value -->
      <brutto>25400.0</brutto>                                      <!-- REQ double  --> <!-- gross total value -->
      <fokonyv>                                                             <!--             --> <!-- general ledger information -->
        <arbevetel>...</arbevetel>                                   <!--     string  --> <!-- sales general ledger ID  -->
        <afa>...</afa>                                                     <!--     string  --> <!-- VAT general ledger ID -->
      </fokonyv>
      <megjegyzes>Példa megjegyzés</megjegyzes>
      <torloKod>123</torloKod>                    <!-- optional: data erasure code per item -->
    </tetel>
    <tetel>
      <megnevezes>Puppy doormat</megnevezes>
      <mennyiseg>2.0</mennyiseg>
      <mennyisegiEgyseg>db</mennyisegiEgyseg>
      <nettoEgysegar>10000</nettoEgysegar>
      <afakulcs>ÁKK</afakulcs>
      <netto>20000.0</netto>
      <afa>5400.0</afa>
      <brutto>25400.0</brutto>
    </tetel>
  </tetelek>
  <!--
	The <kifizetesek> section (payments) is not mandatory, but if present,
	then the sum of the values should be equal with the total amount of the receipt.
  -->
  <kifizetesek>                                                             <!--     string  --> <!-- details of the payment method -->
    <kifizetes>
      <fizetoeszkoz>voucher</fizetoeszkoz>                    <!-- REQ string  --> <!-- name of the legal tender -->
      <osszeg>30000.0</osszeg>                                    <!-- REQ double  --> <!-- paid amount with legal tender -->
      <leiras>OTP SZÉP kártya</leiras>                            <!--     double  --> <!-- description of the legal tender -->
    </kifizetes>
    <kifizetes>
      <fizetoeszkoz>debit card</fizetoeszkoz>
      <osszeg>20800.0</osszeg>
    </kifizetes>
  </kifizetesek>
</xmlnyugtacreate>
