=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/request-xsd-2026-09-11/download/xmlszamlast.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamlast" xmlns:tns="http://www.szamlazz.hu/xmlszamlast" elementFormDefault="qualified">
    <complexType name="vevoTipus">
        <sequence>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszam"   type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszamEU" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="eladoTipus">
        <sequence>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="eszamla" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltesPld" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="aggregator" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="guardian" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="valaszVerzio" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaKulsoAzon" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="fejlecTipus">
        <sequence>
            <element name="szamlaszam"      type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="keltDatum"       type="date"   maxOccurs="1" minOccurs="0"></element>
            <element name="teljesitesDatum" type="date"   maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes"      type="string" maxOccurs="1" minOccurs="0"></element> <!-- itt megadhatod szövegesen a sztornózás okát -->
            <element name="tipus"           type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaSablon"    type="string" maxOccurs="1" minOccurs="0"></element> <!-- Értékkészlet: 'SzlaMost' | 'SzlaAlap' | 'SzlaNoEnv' | 'Szla8cm' | 'SzlaTomb' | 'SzlaFuvarlevelesAlap' -->
        </sequence>
    </complexType>

    <element name="xmlszamlast">
	    <complexType>
	        <sequence>
	            <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="elado" type="tns:eladoTipus" maxOccurs="1" minOccurs="0"></element>
	            <element name="vevo" type="tns:vevoTipus" maxOccurs="1" minOccurs="0"></element>
	        </sequence>
	    </complexType>
    </element>
</schema>

=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/requests/xmlszamlast.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamlast xmlns="http://www.szamlazz.hu/xmlszamlast" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamlast https://www.szamlazz.hu/szamla/docs/xsds/agentst/xmlszamlast.xsd">
    <beallitasok>
        <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
        <eszamla>false</eszamla>
        <!-- e-invoice (true/false) -->
        <szamlaLetoltes>true</szamlaLetoltes>
        <!-- download PDF -->
        <szamlaLetoltesPld>1</szamlaLetoltesPld>
        <!-- download PDF copy or original -->
        <szamlaKulsoAzon></szamlaKulsoAzon><!--     string  --> <!-- The invoice can be identified with this key by the third party system (system which uses the Számla Agent): later the invoice can be queried with this key -->
    </beallitasok>
    <fejlec>
        <!-- header -->
        <szamlaszam>E-TST-2011-1</szamlaszam>
        <!-- invoice number -->
        <keltDatum>2010-09-12</keltDatum>
        <!-- date of issue -->
        <tipus>SS</tipus>
        <!-- type -->
    </fejlec>
    <elado>
        <!-- seller -->
        <emailReplyto>[email protected]</emailReplyto>
        <emailTargy>Email subject</emailTargy>
        <!-- e-mail subject -->
        <emailSzoveg>Lorem ipsum</emailSzoveg>
        <!-- e-mail content -->
    </elado>
    <vevo>
        <!-- buyer -->
        <email>[email protected]</email>
    </vevo>
</xmlszamlast>
