=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/request-xsd-2026-09-11/download/xmlszamlakifiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamlakifiz" xmlns:tns="http://www.szamlazz.hu/xmlszamlakifiz" elementFormDefault="qualified">
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaszam"   type="string"  maxOccurs="1" minOccurs="1"></element>
            <element name="adoszam"      type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="additiv"      type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="aggregator"   type="string"  maxOccurs="1" minOccurs="0"></element>
            <element name="valaszVerzio" type="int" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="kifizetesTipus">
        <sequence>
            <element name="datum"  type="date"   maxOccurs="1" minOccurs="1"></element>
            <element name="jogcim" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="osszeg" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="leiras" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="xmlszamlakifiz">
	    <complexType>
	        <sequence>
	            <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="kifizetes"   type="tns:kifizetesTipus"   maxOccurs="5" minOccurs="0"></element>
	        </sequence>
	    </complexType>
    </element>
</schema>

=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/requests/xmlszamlakifiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamlakifiz xmlns="http://www.szamlazz.hu/xmlszamlakifiz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamlakifiz https://www.szamlazz.hu/szamla/docs/xsds/agentkifiz/xmlszamlakifiz.xsd">
  <beallitasok> <!-- settings -->
    <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
    <szamlaszam>E-TST-2011-1</szamlaszam> <!-- invoice number -->
    <adoszam>12345678-1-13</adoszam> <!-- If you provide the tax number of the issuer of invoice, then the system will match the incoming invoice with the corresponding incoming receipt. -->
    <additiv>false</additiv> <!-- if it is true, then the former credit entries will be retained -->
  </beallitasok>
  <kifizetes> <!-- payment -->
    <datum>2012-01-01</datum><!-- date -->
    <jogcim>készpénz</jogcim><!-- payment type --> 
    <osszeg>1000</osszeg><!-- amount -->
  </kifizetes>
  <kifizetes><!-- an other payment -->
    <datum>2012-01-15</datum>
    <jogcim>átutalás</jogcim>
    <osszeg>2000</osszeg>
    <leiras>Test description</leiras>   <!-- Description, not required -->
  </kifizetes>
</xmlszamlakifiz>
