=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/request-xsd-2026-09-11/download/xmlszamla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamla" xmlns:tns="http://www.szamlazz.hu/xmlszamla" elementFormDefault="qualified">

    <complexType name="vevoTipus">
        <sequence>
            <element name="nev" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="orszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="irsz" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="telepules" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="cim" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="sendEmail" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="adoalany" type="int" maxOccurs="1" minOccurs="0"></element>            
            <element name="adoszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszamEU" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiNev" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiOrszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiIrsz" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiTelepules" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiCim" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyv" type="tns:vevoFokonyvTipus" maxOccurs="1" minOccurs="0"></element>                        
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="telefonszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="vevoFokonyvTipus">
        <sequence>
            <element name="konyvelesDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoAzonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="folyamatosTelj" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumTol" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumIg" type="date" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="eladoTipus">
        <sequence>
            <element name="bank" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="bankszamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="eszamla" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltesPld" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="valaszVerzio" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="aggregator" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="guardian" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="cikkazoninvoice" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaKulsoAzon" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="tetelTipus">
        <sequence>
            <element name="megnevezes" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="mennyiseg" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiEgyseg" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="nettoEgysegar" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afakulcs" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="arresAfaAlap" type="double" maxOccurs="1" minOccurs="0"></element>                        
            <element name="nettoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afaErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="bruttoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="tetelFokonyv" type="tns:tetelFokonyvTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel" type="tns:tetelTipus" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>

    <complexType name="tetelFokonyvTipus">
        <sequence>
            <element name="gazdasagiEsem" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="gazdasagiEsemAfa" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arbevetelFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="afaFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumTol" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumIg" type="date" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fejlecTipus">
        <sequence>
            <element name="keltDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="teljesitesDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizetesiHataridoDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="penznem" type="string" maxOccurs="1"    minOccurs="1"></element>
            <element name="szamlaNyelve" type="tns:szamlaNyelveTipus" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arfolyamBank" type="string" maxOccurs="1" minOccurs="0"></element>   
            <element name="arfolyam" type="double" maxOccurs="1" minOccurs="0"></element>            <!-- Ha arfolyamBank='MNB' ÉS nincs megadva az arfolyam, akkor az MNB aktuális árfolyamát használjuk a számlakészítéskor (automatikus MNB árfolyam beemelés) -->
            <element name="rendelesSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="dijbekeroSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element> <!-- hivatkozás a díjbekérőre -->
            <element name="elolegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="vegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="elolegSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>    <!-- ha a végszámlázandó előlegszámla nem azonosítható a rendelésszámmal, akkor itt megadhatod az előlegszámla számlaszámát -->
            <element name="helyesbitoszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="helyesbitettSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="dijbekero" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="szallitolevel" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="logoExtra" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaszamElotag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetendoKorrekcio" type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetve" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="arresAfa" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="eusAfa" type="boolean" maxOccurs="1" minOccurs="0"></element>            <!-- A számla nem magyar áfát tartalmaz, Online Számla adatküldés nem szükséges. -->
            <element name="szamlaSablon" type="string" maxOccurs="1" minOccurs="0"></element>       <!-- Értékkészlet: 'SzlaMost' | 'SzlaAlap' | 'SzlaNoEnv' | 'Szla8cm' | 'SzlaTomb' | 'SzlaFuvarlevelesAlap' -->
            <element name="elonezetpdf" type="boolean" maxOccurs="1" minOccurs="0"></element>       <!-- bizonylat előnézeti pdf (bizonylat nem készül) -->
            <element name="simpleItems" type="boolean" maxOccurs="1" minOccurs="0"></element>       <!-- egyszerűsített tételek -->
        </sequence>
    </complexType>

    <simpleType name="szamlaNyelveTipus">
        <restriction base="string">
            <enumeration value="hu"></enumeration>
            <enumeration value="en"></enumeration>
            <enumeration value="de"></enumeration>
            <enumeration value="it"></enumeration>
            <enumeration value="ro"></enumeration>
            <enumeration value="sk"></enumeration>
            <enumeration value="hr"></enumeration>
            <enumeration value="fr"></enumeration>
			<enumeration value="es"></enumeration>
			<enumeration value="cz"></enumeration>
			<enumeration value="pl"></enumeration>
			<enumeration value="bg"></enumeration>
			<enumeration value="nl"></enumeration>
			<enumeration value="ru"></enumeration>
			<enumeration value="si"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="transoflexTipus">
        <sequence>
            <!-- a TOF-tól kapott 5 jegyű szám -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="shipmentID" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="countryCode" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="zip" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="service" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="sprinterTipus">
        <sequence>
            <!-- Sprinterrel egyeztetett 3 karakteres rövidítés -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprintertől kapott feladókód, 10 jegyű szám -->
            <element name="feladokod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprinteres iránykód, az a sprinter saját "irányítószáma", pl. "106" -->
            <element name="iranykod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Csomagok száma, ennyi fuvarlevél lesz a számlához összesen -->
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0" ></element>
            <!-- számlánként egyedi, 7-13 karakteres azonosító -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- ez az 1 munkanapos szöveg, többnyire -->
            <element name="szallitasiIdo" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="pppTipus">
        <sequence>
            <!-- PPP-vel egyeztetett 3 karakteres rövidítés -->
            <element name="vonalkodPrefix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- számlánként egyedi, maximum 7 karakteres azonosító -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="mplTipus">
        <sequence>
            <!-- MPL vevőkód -->
            <element name="vevokod" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- A vonalkód ezen string alapján készül -->
            <element name="vonalkod" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- A csomag tömege, tartalmazhat tizedes pontot, ha szükséges -->
            <element name="tomeg" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- A különszolgáltatásokhoz megadható ikonok konfigurációja, ha nincs megadva, akkor egy ikon sem jelenik meg -->
            <element name="kulonszolgaltatasok" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- A fuvarlevélen az értéknyilvánítás mező értéke -->
            <element name="erteknyilvanitas" type="double" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fuvarlevelTipus">
        <sequence>
            <!-- TODO az "uticel" nem használt, 2014.05.30. után eltávolítandó, helyette a sprinter/iranykod mező használandó -->
            <element name="uticel" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- TOF, PPP, SPRINTER, FOXPOST, MPL, GLS, EMPTY lehet az értéke, ha nincs fuvarlevél, akkor nem kell megadni -->
            <element name="futarSzolgalat" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Általános vonalkód megadási lehetőség, ha az alágban nem adjuk meg az adott futárszolgálat 
                 vonalkódjának előállításához szükséges adatokat akkor ezt használja a rendszer. -->
            <element name="vonalkod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- A fuvarlevélen ez a megjegyzés jelenik meg. -->
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Trans-O-Flex futárszolgálat esetén feltöltendő csomópont -->
            <element name="tof" type="tns:transoflexTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- PickPackPoint-ra szállítás esetén kitöltendő csomópont -->
            <element name="ppp" type="tns:pppTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprinter futárszolgálat esetén feltöltendő csomópont -->
            <element name="sprinter" type="tns:sprinterTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- MPL esetén feltöltendő csomópont -->
            <element name="mpl" type="tns:mplTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="xmlszamla">
        <complexType>
            <sequence>
                <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="elado" type="tns:eladoTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="vevo" type="tns:vevoTipus" maxOccurs="1" minOccurs="1"></element>
                <!-- A fuvarlevél nem kötelező, csak akkor add meg ha tudod pontosan mi ez, és olyan számlaképet használsz ami meg tudja jeleníteni -->
                <element name="fuvarlevel" type="tns:fuvarlevelTipus" maxOccurs="1" minOccurs="0"></element>
                <element name="tetelek" type="tns:tetelekTipus" maxOccurs="1" minOccurs="1"></element>
            </sequence>
        </complexType>
    </element>

</schema>

=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/requests/xmlszamla.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla https://www.szamlazz.hu/szamla/docs/xsds/agent/xmlszamla.xsd">
    <beallitasok>
        <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
        <eszamla>true</eszamla>
        <!-- „true” in case you need to create an e-invoice -->
        <szamlaLetoltes>true</szamlaLetoltes>
        <!-- „true” in case you would like to get the 
                                             PDF invoice in the response -->
        <valaszVerzio>1</valaszVerzio>
        <!-- 1: gives a simple text or PDF as answer. 
                                             2: xml answer, in case you asked for the PDF as well,
                                                it will be included in the XML with base64 coding.
                                         -->
        <aggregator></aggregator>
        <!-- omit this tag -->
        <szamlaKulsoAzon></szamlaKulsoAzon> <!--     string  --> <!-- The invoice can be identified with this key by the third party system (system which uses the Számla Agent): later the invoice can be queried with this key. Important: The invoice will only have this external identifier if you send this field when creating the invoice. -->
    </beallitasok>
    <fejlec>
        <!-- header -->
        <keltDatum>2020-01-20</keltDatum>
        <!-- creating date, in this exact format -->
        <teljesitesDatum>2020-01-20</teljesitesDatum>
        <!-- payment date -->
        <fizetesiHataridoDatum>2020-01-20</fizetesiHataridoDatum>
        <!-- due date -->
        <fizmod>Átutalás</fizmod>
        <!-- payment type: it can be seen in case you create the invoice 
                                 from browser -->
        <penznem>HUF</penznem>
        <!-- currency: it can be seen in case you create the invoice 
                                 from browser -->
        <szamlaNyelve>hu</szamlaNyelve>
        <!-- language of invoice, can  be: de, en, it, hu, fr, ro, sk, hr
                                   -->
        <megjegyzes>Invoce comment</megjegyzes>
        <!-- comment of the invoice -->
        <arfolyamBank>MNB</arfolyamBank>
        <!-- name of bank: in case of invoice about other currency 
                                          than HUF you have to display which bank’s exchange rates 
                                          did we use to calculate VAT -->
        <arfolyam>0.0</arfolyam>
        <!-- exchange rate: in case of invoice about other currency 
                                          than HUF you have to display which bank’s exchange rates 
                                          did we use to calculate VAT -->
        <rendelesSzam></rendelesSzam>
        <!-- order number -->
        <dijbekeroSzamlaszam></dijbekeroSzamlaszam>
        <!-- reference to pro forma invoice number -->
        <elolegszamla>false</elolegszamla>
        <!-- deposit invoice -->
        <vegszamla>false</vegszamla>
        <!-- invoice (after a deposit invoice) -->
        <helyesbitoszamla>false</helyesbitoszamla>
        <!-- correction invoice -->
        <helyesbitettSzamlaszam></helyesbitettSzamlaszam>
        <!-- the number of the corrected invoice -->
        <dijbekero>false</dijbekero>
        <!-- proform invoice -->
        <szamlaszamElotag></szamlaszamElotag>
        <!-- One of the prefixes from the invoice pad menu  -->
    </fejlec>
    <elado>
        <!-- Details of the merchant-->
        <bank>BB</bank>
        <!-- bank name -->
        <bankszamlaszam>11111111-22222222-33333333</bankszamlaszam>
        <!-- bank account -->
        <emailReplyto></emailReplyto>
        <!-- reply e-mail address -->
        <emailTargy>Invoice notification</emailTargy>
        <!-- e-mail subject -->
        <emailSzoveg>mail text</emailSzoveg>
        <!-- text of e-mail -->
    </elado>
    <vevo>
        <!--Buyer details -->
        <nev>Kovacs Bt.</nev>
        <!-- name -->
        <irsz>2030</irsz>
        <!-- ZIP code -->
        <telepules>Érd</telepules>
        <!-- city -->
        <cim>Tárnoki út 23.</cim>
        <!-- address -->
        <email>[email protected]</email>
        <!-- e-mail address, if given, we will send the invoice to this mail address -->
        <sendEmail>false</sendEmail>
        <!-- should we send the e-mail to the customer (by email) -->
        <adoszam>12345678-1-42</adoszam>
        <!-- fiscal number/tax number -->
        <postazasiNev>Kovács Bt. mailing name</postazasiNev>
        <!--delivery name/postal name -->
        <postazasiIrsz>2040</postazasiIrsz>
        <!--delivery ZIP code/postal ZIP code -->
        <postazasiTelepules>Budaörs</postazasiTelepules>
        <!--delivery city/postal city -->
        <postazasiCim>Szivárvány utca 8.</postazasiCim>
        <!--delivery address/postal address -->
        <azonosito>1234</azonosito>
        <!-- If you have a subscription in your billing account,
     you can assign a unique identifier to your partners on their profile page
     in the Beállítások -Partnerek menu. It's important that each identifier
     is linked to only one partner! DO NOT use an identifier that has already
     been assigned to another customer in your billing account's partner database. -->
        <telefonszam>Tel:+3630-555-55-55, Fax:+3623-555-555</telefonszam>
        <!-- phone number -->
        <megjegyzes>Call extension 214 from the reception</megjegyzes>
        <!-- comment -->
    </vevo>
    <fuvarlevel>
        <!-- waybill/confinement note, you do not need this: omit the entire tag -->
        <uticel></uticel>
        <futarSzolgalat></futarSzolgalat>
    </fuvarlevel>
    <tetelek>
        <!-- items on invoice -->
        <tetel>
            <!-- item 1 -->
            <megnevezes>Elado izé</megnevezes>
            <!-- name -->
            <mennyiseg>1.0</mennyiseg>
            <!-- quantity -->
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <!-- unit of quantity -->
            <nettoEgysegar>10000</nettoEgysegar>
            <!-- unit price -->
            <afakulcs>27</afakulcs>
            <!-- VAT rate -->
            <nettoErtek>10000.0</nettoErtek>
            <!-- net price -->
            <afaErtek>2700.0</afaErtek>
            <!-- VAT amount -->
            <bruttoErtek>12700.0</bruttoErtek>
            <!-- gross amount -->
            <megjegyzes>lorem ipsum</megjegyzes>
            <!-- comment for item -->
            <torloKod>123</torloKod>
            <!-- optional: data erasure code per item -->
        </tetel>
        <tetel>
            <!-- item 2, details are same as above -->
            <megnevezes>Elado izé 2</megnevezes>
            <mennyiseg>2.0</mennyiseg>
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <nettoEgysegar>10000</nettoEgysegar>
            <afakulcs>27</afakulcs>
            <nettoErtek>20000.0</nettoErtek>
            <afaErtek>5400.0</afaErtek>
            <bruttoErtek>25400.0</bruttoErtek>
            <megjegyzes>lorem ipsum 2</megjegyzes>
        </tetel>
    </tetelek>
</xmlszamla>
