=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/request-xsd-2026-09-11/en-inline/xmlnyugtasend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlnyugtasend" xmlns:tns="http://www.szamlazz.hu/xmlnyugtasend" elementFormDefault="qualified">
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="fejlecTipus">
        <sequence>
            <!-- Receipt number to send. -->
            <element name="nyugtaszam" type="string" maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>
    <!-- Optional: send receipt by e-mail. If omitted, no e-mail is sent. -->
    <complexType name="emailKuldes">
        <sequence>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <element name="xmlnyugtasend">
        <complexType>
            <sequence>
                <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="emailKuldes" type="tns:emailKuldes" maxOccurs="1" minOccurs="0"></element>
            </sequence>
        </complexType>
    </element>
</schema>

=== sagikazarmark/szamlazz-rs/fixtures/upstream/agent/requests/xmlnyugtasend.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlnyugtasend xmlns="http://www.szamlazz.hu/xmlnyugtasend" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlnyugtasend http://www.szamlazz.hu/docs/xsds/nyugtasend/xmlnyugtasend.xsd">
  <beallitasok>                                                            <!-- REQ string -->
    <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
  </beallitasok>
  <fejlec>
    <!-- e-mail notification available only for already issued receipts -->
    <nyugtaszam>NYGT-2020-1</nyugtaszam>             <!-- REQ string --> <!-- Receipt ID -->
  </fejlec>
  <!-- e-mail configuration-->
  <emailKuldes>
    <!-- e-mail details, if not defined, the previous e-mail will be sent  -->
    <email>[email protected]</email>                       <!--     string --> <!-- customer e-mail address (recipient)	-->
    <emailReplyto>[email protected]</emailReplyto> <!--     string --> <!-- reply-to  address, the customer will reply to this address -->
    <emailTargy>Email tárgya</emailTargy>                 <!--     string --> <!-- e-mail subject -->
    <emailSzoveg>                                                       <!--     string --> <!-- e-mail body -->
Text in the e-mail.
Signature
    </emailSzoveg>
  </emailKuldes>
</xmlnyugtasend>
